[package]
name = "cram-hal-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utralib = { version = "0.1.24", optional = true, default-features = false, features = [
    "cramium-soc",
] }
xous-api-names = "0.9.58"
xous-api-ticktimer = "0.9.56"
xous = "0.9.60"
xous-ipc = "0.9.60"
log-server = { package = "xous-api-log", version = "0.1.56" }
log = "0.4.14"
cramium-hal = { path = "../../libs/cramium-hal", features = [
    "derive-rkyv",
    "std",
] }
xous-pl230 = { path = "../../libs/xous-pl230", features = ["cramium-soc"] }
xous-pio = { path = "../../libs/xous-pio", default-features = false, features = [
    "cramium-soc",
] }
pio-proc = "0.2.2"
pio = "0.2.1"

num-derive = { version = "0.3.3", default-features = false }
num-traits = { version = "0.2.14", default-features = false }
rkyv = { version = "0.4.3", default-features = false, features = [
    "const_generics",
] }

[features]
app-uart = []
swap = []
# add this feature to enable pre-emption
quantum-timer = ["utralib"]
default = ["quantum-timer", "app-uart"]
