[package]
name = "net"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Network middleware"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous = "0.9.55"
xous-ipc = "0.9.55"
log-server = { package = "xous-api-log", version = "0.1.51" }
ticktimer-server = { package = "xous-api-ticktimer", version = "0.9.51" }
xous-names = { package = "xous-api-names", version = "0.9.53" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
susres = {package = "xous-api-susres", version = "0.9.51"}
#rkyv = "0.7.18"
rkyv = {version = "0.4.3", features = ["const_generics"], default-features = false}
llio = {path = "../llio"}
com = {path = "../com"}
byteorder = { version = "1.0", default-features = false }
trng = {path = "../trng"}
com_rs = { git = "https://github.com/betrusted-io/com_rs", rev = "891bdd3ca8e41f81510d112483e178aea3e3a921" }
modals = {path = "../modals"}
locales = {path = "../../locales"}
utralib = { version = "0.1.23", optional = true, default-features = false }

# for automatic SSID management and AP list storage
pddb = {path = "../pddb"}

xous-semver = "0.1.2"

[dependencies.smoltcp]
# some historical notes for development on branches in the future
# path = "../../../smoltcp"
git = "https://github.com/smoltcp-rs/smoltcp.git"
branch = "main"
#git = "https://github.com/betrusted-io/smoltcp.git"
#rev = "35c8ec3d30c846442a1faae01fb0537641aef898"
# 0.8.1 drops the rand_core dep and doesn't have the breaking IPv4 change (see issue #613)
# version = "0.8.1"
default-features = false
features = [
  "std", "log", # needed for `cargo test --no-default-features --features default` :/
  "medium-ethernet", "medium-ip",
  "phy-raw_socket",
  "proto-ipv4", "proto-ipv6",
  "socket-raw", "socket-icmp", "socket-udp", "socket-tcp",
]
# tracking main branch changes:
# works with:
#  - edfdb23243a973d458397a2b4e76f527bacb1fd6
# broken at:
#  - e893a17fc761a9c1b34647ff09102993336cc341 (can't get past the first ping)
#  - 9624adf20cbeaf627e907a87b4fdf74e8f3154fb (broken after the third attempt to ping?)

[features]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
renode-minimal = []
default = []
