[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Xous microkernel OS inter-process name resolution server"
edition = "2018"
name = "xous-swapper"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/betrusted-io/xous-core/"
homepage = "https://betrusted.io/"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous-api-names = "0.9.56"
log-server = { package = "xous-api-log", version = "0.1.54" }
xous = { version = "0.9.58", features = ["swap"] }
xous-ipc = "0.9.58"
num-derive = { version = "0.3.3", default-features = false }
num-traits = { version = "0.2.14", default-features = false }
log = "0.4.14"

utralib = { version = "0.1.24", optional = true, default-features = false }

[target.'cfg(any(windows,unix))'.dependencies]

[features]
cramium-soc = ["utralib/cramium-soc"]
cramium-fpga = ["utralib/cramium-fpga"]
precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]

# for now, debug-print only works on Precursor targets
debug-print = []
default = ["debug-print"]
