[package]
name = "spawn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xous = "0.9.59"
log-server = { package = "xous-api-log", version = "0.1.55", features = ["nostd"] }
log = "0.4.17"
